src/types.ts
src/webpack/index.ts

feat: `resolveId` supports Rollup externals

---

package.json

Should stay at 5 since it is officially supported 🌴

Fixed webpack peer dependency warnings

---

README.md

chore(readme): fix double asterisk

---

src/webpack/index.ts

fix: `buildEnd` hook

---

src/rollup/index.ts
src/vite/index.ts

fix: #62
This behavior is not as expected

fix: rollup options  were passed to vite plugin

---

src/webpack/utils.ts

I still with pnpm 6 and so I cannot test it...
EDIT: check also #84 I'm not an expert on webpack and maybe this PR and 84 are both wrong...
closes #83

fix(webpack): use path separator instead backslash

---

src/webpack/index.ts
src/webpack/loaders/transform.ts

Fixes https://github.com/unjs/unplugin/pull/144#issuecomment-1204316085

fix: fix webpack 4 by not using loader options

---

src/types.ts

fix(types): align source map with rollup

---

.github/workflows/ci.yml

ci: add node 18

---

package.json

fix: add types to export map

---

src/define.ts

fix(types): add Nested generic to createUnplugin

---

src/esbuild/index.ts
src/types.ts

Adding `build` to `meta` for esbuild

feat(esbuild): add plugin build context to meta

---

package.json

reference: https://www.typescriptlang.org/docs/handbook/esm-node.html#packagejson-exports-imports-and-self-referencing

fix: move types to the first field

---

README.md

Add universal webfont loader to readme list

feat: add unplugin-fonts

---

README.md

https://github.com/baiwusanyu-c/unplugin-vue-cssvars

docs: added uplugin-vue-cssvars

---

README.md
docs/guide/index.md
docs/index.md

fix: farmfe link

---

docs/guide/index.md

Fix typo in docs

---

src/rspack/index.ts
src/webpack/index.ts

Fix https://github.com/unjs/unplugin/issues/389

fix: await writeBundle hook in webpack and rspack

---

src/esbuild/index.ts
src/esbuild/utils.ts
src/farm/context.ts
src/farm/index.ts
src/rspack/context.ts
src/rspack/index.ts
src/rspack/loaders/load.ts
src/rspack/loaders/transform.ts
src/types.ts
src/utils.ts
src/webpack/context.ts
src/webpack/index.ts
src/webpack/loaders/load.ts
src/webpack/loaders/transform.ts

feat: expose native build context

---

docs/.vitepress/config.ts

docs: fix github link

---

src/rspack/index.ts

chore: fix tiny typo

---

package.json
pnpm-lock.yaml
src/rspack/index.ts
src/rspack/loaders/load.ts
src/rspack/loaders/transform.ts
src/types.ts
src/utils.ts
src/webpack/context.ts
src/webpack/index.ts
src/webpack/loaders/load.ts
src/webpack/loaders/transform.ts
test/unit-tests/resolve-id/resolve-id.test.ts

refactor!: drop webpack 4

---

.vscode/extensions.json
.vscode/settings.json
package.json

resolves https://github.com/unjs/unplugin/issues/490
refs
- https://github.com/antfu/starter-ts/blob/95557b44ae3b120310165e0d7b825be3fe23eec7/package.json#L57-L62
- https://github.com/antfu/starter-ts/tree/main/.vscode

chore: fix vscode settings

---

test/unit-tests/esbuild/utils.test.ts
vitest.config.ts

resolves https://github.com/unjs/unplugin/issues/489 but to be continue...

test: add test for esbuild/utils.ts

---

test/unit-tests/rolldown/index.test.ts
test/unit-tests/unloader/index.test.ts
test/unit-tests/utils/context.test.ts

continue https://github.com/unjs/unplugin/pull/492

test: add test for rolldown/unloader/utils

---

docs/guide/index.md
package.json
pnpm-lock.yaml
src/esbuild/index.ts
src/farm/index.ts
src/rollup/index.ts
src/rspack/index.ts
src/rspack/loaders/load.ts
src/rspack/loaders/transform.ts
src/types.ts
src/utils/filter.ts
src/utils/webpack-like.ts
src/webpack/index.ts
src/webpack/loaders/load.ts
src/webpack/loaders/transform.ts
test/unit-tests/filter/filter.test.ts
test/unit-tests/filter/test-src/entry.js
test/unit-tests/filter/test-src/mod.js
test/unit-tests/filter/test-src/not-expect.js
test/unit-tests/utils.ts

Thanks to https://github.com/rollup/rollup/pull/5882 by @sapphi-red

feat: filters

---

src/rspack/context.ts
test/unit-tests/rspack/context.test.ts
test/unit-tests/rspack/loaders/load.test.ts
test/unit-tests/rspack/loaders/transform.test.ts

continue https://github.com/unjs/unplugin/pull/492

test: add test for rspack

---

test/unit-tests/farm/context.test.ts
test/unit-tests/farm/index.test.ts
test/unit-tests/farm/utils.test.ts

continue https://github.com/unjs/unplugin/pull/492
this PR is last order.
if merged https://github.com/unjs/unplugin/pull/496,https://github.com/unjs/unplugin/pull/497, https://github.com/unjs/unplugin/pull/498

test: add test for farm

---

src/rspack/index.ts
src/types.ts
src/webpack/index.ts

fix(rspack): prevent vfs concurrency issues

---

src/rspack/index.ts
src/types.ts
src/webpack/index.ts

should resolve https://github.com/unocss/unocss/issues/4660

fix: rollback webpack __vfsModules to a Set

---

src/rspack/loaders/load.ts

I basically ported over what has been done in https://github.com/unjs/unplugin/pull/482
Should solve #535

fix(rspack): prevents an unhandled promise rejection when throwing in the async loader

---

src/rspack/utils.ts

> This PR appears to have broken other apps https://github.com/TanStack/router/issues/5023
Removing the cleanup handlers added in #538.

fix(rspack): remove virtual plugin cleanup signal handlers
