unjs/unplugin

- src/webpack/index.ts
This PR just make the function in tapPromise be async, so that they can return promise properly.
see #41
> fix: webpack hook tapPromise must return Promise object

- README.md
- package.json
- scripts/buildFixtures.ts
- src/define.ts
- src/esbuild/index.ts
- src/esbuild/utils.ts
- src/types.ts
- test/fixtures/transform/__test__/build.test.ts
- test/fixtures/transform/esbuild.config.js
- test/fixtures/virtual-module/__test__/build.test.ts
- test/fixtures/virtual-module/esbuild.config.js
- yarn.lock
This pr adds esbuild support for unplugin, which resolves #25 .
Some Todos:
Hope to hear your thoughts!
> feat: support esbuild

- src/esbuild/utils.ts
fix error 
```
✘ [ERROR] [plugin unplugin-vue] Cannot redefine property: toString
at Function.defineProperty (<anonymous>)
at fixSourceMap (file://some/path/node_modules/.pnpm/unplugin@0.3.0_f1163fc619aae5be7a2291f98077607c/node_modules/unplugin/dist/index.mjs:472:10)
```
> fix: avoid redefining property

- src/esbuild/utils.ts
filter ou illegal sourcemap like this
```js
{ mappings: '' }
```
> fix: filter out illegal sourcemap items

- README.md
- package.json
- pnpm-lock.yaml
- src/esbuild/index.ts
- src/types.ts
- src/webpack/index.ts
Add support for [`watchChange`](https://rollupjs.org/guide/en/#watchchange) hook, [`this.addWatchFile`](https://rollupjs.org/guide/en/#thisaddwatchfile), [`this.emitFile`](https://rollupjs.org/guide/en/#thisemitfile), and [`this.getWatchFiles`](https://rollupjs.org/guide/en/#thisgetwatchfiles). The last three are provided whithin the `this` context for the [`buildStart`](https://rollupjs.org/guide/en/#buildstart) hook. Closes #53.
> feat: add watch hook and context functions

- README.md
- src/esbuild/index.ts
- src/types.ts
- src/webpack/genContext.ts
- src/webpack/index.ts
- src/webpack/loaders/load.ts
- src/webpack/loaders/transform.ts
- Add context functions to [`buildEnd`](https://rollupjs.org/guide/en/#buildend), [`transform`](https://rollupjs.org/guide/en/#transformers), [`load`](https://rollupjs.org/guide/en/#load), and [`watchChange`](https://rollupjs.org/guide/en/#watchchange) hooks.
- Fix async hooks.
- Add example plugin with context functions.
- Fix esbuild [`this.emitFile`](https://rollupjs.org/guide/en/#thisemitfile) issue on build without directory.
> feat: add context functions to more hooks, fix async hooks

- src/webpack/index.ts
I could be missing something, it seems more reasonable to use resolved id so that plugin author have more control over `resolveId` hook.
Have a use case for virtual routes as below:
```ts
// App.tsx
import routes from '~routes'
// webpack.config.js
// `~routes` w/o extension will be matched by CRA's file-loader 
// https://github.com/facebook/create-react-app/blob/eee8491d57d67dd76f0806a7512eaba2ce9c36f0/packages/react-scripts/config/webpack.config.js#L509
// Plugin.ts
{
resolveId(id: string) {
if (id === '~routes') 
return '~routes.mjs'
return null 
}
}
```
###
> feat: respect resolved id instead of raw request id

- README.md
Previously it was `esbuild-plugin-properties`, migrated to unplugin to adapt to more bundlers.
https://github.com/pd4d10/unplugin-properties
> docs: add an example

- README.md
I was confused a bit if I can use warm and error methods...
Looks it is supported everywhere.
> docs: added warn and error context methods to readme

- README.md
Add an example [`unplugin-parcel-css`](https://github.com/ssssota/unplugin-parcel-css)!
Thank you.
> docs: add example `unplugin-parcel-css`

- src/esbuild/index.ts
- src/types.ts
- src/webpack/index.ts
- test/unit-tests/resolve-id/resolve-id.test.ts
- test/unit-tests/resolve-id/test-src/default-export.js
- test/unit-tests/resolve-id/test-src/entry.js
- test/unit-tests/resolve-id/test-src/named-export.js
- test/unit-tests/resolve-id/test-src/proxy-export.js
This PR adds the `isEntry` flag of rollup's [`resolveId` hook](https://rollupjs.org/guide/en/#resolveid) to all of unplugin's supported tools.
- I "cleaned up" the webpack integration a bit. It didn't get a lot cleaner but the TS type inference got a bit better.
- Added a unit test stup for the `resolveId` hook. We could use similar setups to test the other hooks.
> feat: add `isEntry` flag to `resolveId` hook

- src/esbuild/index.ts
- src/webpack/index.ts
- test/fixtures/transform/__test__/build.test.ts
- test/fixtures/transform/src/main.js
- test/fixtures/transform/src/query.js
- test/fixtures/transform/unplugin.js
> fix: webpack and esbuild query string support

- src/esbuild/index.ts
- src/globals.d.ts
- src/utils.ts
- src/vite/index.ts
- src/webpack/index.ts
- src/webpack/loaders/load.ts
- src/webpack/utils.ts
- test/unit-tests/id-consistency/id-consistency.test.ts
- test/unit-tests/id-consistency/test-src/default-export.js
- test/unit-tests/id-consistency/test-src/entry.js
- test/unit-tests/id-consistency/test-src/proxy-export.js
- test/unit-tests/id-consistency/test-src/sub-folder/named-export.js
- test/unit-tests/resolve-id-external/resolve-id-external.test.ts
- test/unit-tests/resolve-id-external/test-src/entry.js
- test/unit-tests/resolve-id-external/test-src/internal-module.js
- test/unit-tests/resolve-id/resolve-id.test.ts
- test/unit-tests/utils.ts
- tsup.config.ts
- vitest.config.ts
This PR fixes a behavior where the passed `id` args aren't the same across bundlers and hook calls. It also adds tests to ensure this behavior.
In detail:
- Don't run the `resolveId` hook in esbuild when the module is marked as external. (mirrors rollup's behavior)
- Run `load` for all loaded modules in webpack. I don't actually know if this change is problematic. I would love some insight into why the check for virtual modules was introduced in the first place.
- Introduce a build-time flag, since webpack loaders and unit tests are a bit tricky with path resolution.
- Replace the slash/backslash utilities with a more sustainable solution that always normalizes absolute paths/ids to OS conform paths
- URL encode the module id in webpack before passing it to loader (avoids path …
> fix: ensure consistent `id`s across hooks and bundlers

- src/webpack/index.ts
fix: https://github.com/unocss/unocss/issues/1429
Actually, I don't know why there didn't have this problem(infinite compile) before. But by my test, do not repeat reset `__vfsModules` value is works.
> fix(webpack): avoid repeat set __vfsModules value

- README.md
Resolves #40
I changed wording in README, and added a section to summarize authoring conventions, based on Vite's documentation ([ref1](https://vitejs.dev/guide/api-plugin.html#plugins-config) for naming, [ref2](https://vitejs.dev/guide/api-plugin.html#conventions) for conventions) and [Unplugin starter template](https://github.com/antfu/unplugin-starter) for conventions.
I believe it's reasonable to add Conventions section, because we can manage related information in one place.
This is my very first PR for this repository, so please let me know if I'm missing some rules or conventions.
> docs: add conventions

- README.md
This package is meant to make creating an unplugin even easier. You execute the command and follow the prompts to customize the generated project. Any suggestions from @antfu or anyone else for improvements would be appreciated. I want to make this one of the easiest ways to get started with unplugin.
> docs: add create-unplugin to starter templates

- README.md
- src/esbuild/index.ts
- src/types.ts
- src/webpack/index.ts
- test/unit-tests/utils.ts
- test/unit-tests/write-bundle/.gitignore
- test/unit-tests/write-bundle/test-src/entry.js
- test/unit-tests/write-bundle/test-src/import.js
- test/unit-tests/write-bundle/write-bundle.test.ts
This PR adds the most basic form of the `writeBundle` hook.
The reason for having it even in that form is that the `buildEnd` hook is called before any files have been written to disk and the added `writeBundle` hook could be used to have plugin code run after bundles have been written.
Also adds some tests to verify that the hook has run *after* assets have been written to disk.
> feat: add `writeBundle` hook

- README.md
[`unplugin-sentry`](https://github.com/kricsleo/unplugin-sentry) is an all-in-one plugin(based on `unplugin`) for projects to work with [Sentry](https://docs.sentry.io/). Hopes to add it to the community showcases. Any question is welcome!
> docs: add a community showcase

- README.md
- src/define.ts
The current `createUnplugin` will not allow you to tree-shake unused code if you want to distribute individual plugins for each platform. I.e. the output may still contain webpack code even though you just want to create a rollup plugin.
This PR adds top-level methods to create plugins for the individual bundlers that are tree-shakable if unused.
> feat: add top-level functions to create platform-specific plugins

- src/rspack/index.ts
buildStart looks supported in the readme, but it doesn't actually support that. So I copied it directly from the webpack and tried it and it worked.
> feat(rspack): support buildStart

- src/rspack/index.ts
- src/webpack/index.ts
- test/fixtures/load/__test__/build.test.ts
- test/fixtures/load/esbuild.config.js
- test/fixtures/load/rollup.config.js
- test/fixtures/load/rspack.config.js
- test/fixtures/load/src/main.js
- test/fixtures/load/src/msg.js
- test/fixtures/load/unplugin.js
- test/fixtures/load/vite.config.js
- test/fixtures/load/webpack.config.js
webpack | Rspack, The load hook should be executed earlier than the transform hook
I'm not sure if I'm doing this as a Breaking change
[minimal reproduction](https://github.com/qiYuei/deef-webpack)
> fix: adjust webpack rspack hooks sequence

- README.md
- src/esbuild/index.ts
- src/types.ts
Vite has a [`config` option](https://vitejs.dev/guide/api-plugin#config) that lets plugins view and/or modify the configuration.
I've been missing this option in esbuild. This PR adds a similar `config` option, which gets passed in [`build.initialOptions`](https://esbuild.github.io/plugins/#build-options).
> feat: esbuild config option to modify build options

- src/webpack/context.ts
- src/webpack/index.ts
- src/webpack/loaders/load.ts
- src/webpack/loaders/transform.ts
The current implementation of `addWatchFile` in webpack uses the `compilation.fileDependencies`, which does result in the file being watched, but does not associate it with the current module being processed by a loader. As a result, webpack does not trigger recompilation of that module.
This PR fixes this by using the loader context's `addDependency` function, which both watches the file and adds it as a dependency of the module so it triggers recompilation. A similar API is used for resolvers as well.
Not sure if there is a way to unit test this: I didn't see any tests for watch behavior. However I did test this by npm linking into a project and using the `addWatchFile` in a webpack project.
> fix: use webpack loader context to implement addWatchFile

- src/esbuild/utils.ts
n/a
When calling `this.emitFile({fileName: 'subdir/foo.d.ts', source, type: 'asset'})`, Rollup [recursively makes the directory](https://github.com/rollup/rollup/blob/c9b3655ec25d08f5182feb3d118cc676940f1549/src/rollup/rollup.ts#L296) `dist/subdir` if necessary.
But unplugin's esbuild plugin does not; currently, it just makes the directory `dist` (where `dist` is the `outdir` option). If `dist/subdir` doesn't exit, the emit crashes.
This small PR changes the esbuild emitFile `mkdir` call to apply to the full directory (`dist/subdir` in the example, instead of `dist`).
> fix: esbuild emitFile should mkdir subdirectories too

- src/esbuild/index.ts
> fix: fix build syntax error in < node16

- package.json
- pnpm-lock.yaml
- src/define.ts
- src/rolldown/index.ts
- src/types.ts
Add [Rolldown](https://github.com/rolldown-rs/rolldown) support
> [!CAUTION]
> Rolldown is currently under active development and might not be ready to support plugins yet.
> feat: add rolldown support

- README.md
- docs/.vitepress/constance.ts
- docs/README.md
> docs: update site link

- src/esbuild/index.ts
Brought up over here https://github.com/devongovett/unplugin-parcel-macros/issues/4
The `type` cast to `any` on https://github.com/unjs/unplugin/blob/867b71d8f52a6fe8b32b0de801cdf3351da6ff79/src/esbuild/index.ts#L288 was hiding a bug where the result could be a string. When it was, you'd get an error such as `Cannot create property 'sourcesContent' on string '{"version":3,"sources":["test.js"]`
I'm not quite sure how to write a test for this, though, as I'm not entirely sure how this actually occurs other than possibly when passed across languages, ie rust to js. Any pointers are welcome.
I'd thought to change https://github.com/unjs/unplugin/blob/867b71d8f52a6fe8b32b0de801cdf3351da6ff79/test/fixtures/transform/unplugin.js#L35 by wrapping it in a JSON.stringify, but that didn't work.
> fix(esbuild): sourcemaps in transform result can be a string

- src/rspack/index.ts
- src/webpack/index.ts
https://github.com/unjs/unplugin/issues/375
Build tools can decide to resolve from wherever they want, and it's not guaranteed that the place they resolve from is the user's current working directory. 
For example this reproduction of the failure case where in embroider (which uses a `node_modules/.embroider/` directory for the root -- and I imagine svelte apps, too with their `.svelte` directory)
https://github.com/embroider-build/embroider/issues/1843
Repro here: https://github.com/NullVoxPopuli/embroider-3--unplugin-plugin-loads-app-files
Here is a patched version of unplugin which allows the build to succeed: https://github.com/NullVoxPopuli/embroider-3--unplugin-plugin-loads-app-files/pull/1
> fix(webpack,rspack): incorrect assumption about the current working directory in webpack and rspack

- src/types.ts
fix #391
Hello :wave: this PR adds `void` to `TransformResult` to avoid forcing users to specify `undefined` when `transform` does not return anything
> fix: allow void in TransformResult

- src/esbuild/utils.ts
Currently, if you:
* use esbuild mode of an unplugin, and
* return a `map` from a `load` handler, where the `map` is produced by `JSON.parse`ing a JSON sourcemap (e.g. as returned by esbuild itself),
then unplugin ends up outputting a sourcemap of `[object Object]` (encoded in base64) because it overrides `toUrl` but not `toString` that's inherited from the `Object` prototype.
I believe the simple fix in this PR (use `Object.hasOwn` instead of `in`, to avoid checking prototypes) is what is intended, and it fixed the bug I was encountering.
Full (but not small) reproduction: https://github.com/DanielXMoore/Civet/tree/main/integration/unplugin-examples/esbuild with `sourceMap: true` added to `options` in `esbuild.js`, and v0.7.22 of `@danielx/civet` (I'm about to release a workaround).
> fix(esbuild): object sourcemap by overriding Object.prototype.toString

- package.json
- pnpm-lock.yaml
- `chokidar` was added in https://github.com/unjs/unplugin/pull/55 but no longer needed since https://github.com/unjs/unplugin/pull/284
> Remove unused chokidar dependency

- src/rspack/index.ts
- src/webpack/index.ts
- test/fixtures/virtual-module/unplugin.js
https://github.com/unjs/unplugin/commit/ab51c6f9ef8822db2d3e87434f470183c760958c causes a bug about virtual module support in rspack, related https://github.com/web-infra-dev/rspack/issues/7787
Since `dist/rspack/vitual.js` (the placeholder module for the virtual module) is published with the unplugin package, so `unplugin/package.json#type` will affect the moduleType of virtual module:
- `type: "commonjs" => moduleType: "javascript/dynamic"` (current behavior, which will cause an error when rspack parsing any virtual module with esm syntax)
- `type: "module" => moduleType: "javascript/esm"`
- `unspecified => moduleType: "javascript/auto"`
Actually in rollup, it does not make such detailed distinctions for javascript, [all javascript will be treated as …
> fix: undetermistic module type for virtual module

- src/rspack/index.ts
- src/rspack/utils.ts
- src/rspack/virtual.js
- tsup.config.ts
fix #415
This PR uses `FakeVirtualModules` to write virtual module to disk (under `.virtual` directory), @hardfist is working on a real `VirtualModulesPlugin` for Rspack, which will avoid writing file to disk, I will send another PR to switch to it once it's released
> fix: match resource for virtual module

- src/rspack/index.ts
- src/webpack/index.ts
- test/unit-tests/virtual-id/test-src/entry.js
- test/unit-tests/virtual-id/test-src/imported.js
- test/unit-tests/virtual-id/virtual-id.test.ts
I found that unplugin in webpack mode (and rspack mode) virtualized my resolved filenames (because I added a custom extension and the file didn't exist), but didn't unvirtualize the filenames when giving them back to me via the `importer` second argument to `resolveId`.
This simple PR fixes this issue by decoding virtualized filenames in `importer`, so that webpack and rspack behave like other systems. Includes a test with a simple mangling of filename (adding an extra `.js` to end of `.js` files).
> fix: Unvirtualize `importer` paths in webpack and rspack

- .github/workflows/ci.yml
I think we may add node v22 also since it is the latest now.
> ci: add node v22

- src/rspack/index.ts
fix 
```shell
plugin.__vfs.writeModule(id, code);
^
TypeError: Cannot read properties of undefined (reading 'writeModule')
```
> fix(rspack): plugin.__vfs is undefined

- src/farm/context.ts
hi @sxzz  
farm modifies the `moduleId` of the `second parameter` by default to recompile the `first parameter` and store the first parameter in `watch_graph`.
> fix(farm): modify the parameter order of addWatchFile

- src/rspack/loaders/transform.ts
- src/webpack/loaders/transform.ts
Add error handling for the plugin's `transform` in the Rspack loader.
Wrapping the `plugin.transform.call()` in a try-catch block to ensure that any errors thrown during the transformation process are properly captured and passed to Rspack's error handling mechanism.
I made the same changes to the webpack loader to keep it consistent.
resolve https://github.com/web-infra-dev/rsbuild/issues/4789
- dev without `try...catch` (process exit):
- dev with `try...catch` (the error is emit by Rspack and this did not break the dev build):
> fix: add error handling to transform for Rspack and webpack

- src/rspack/utils.ts
Wait for all the compilers to shutdown before deleting the vfs folder.
resolves #509
> fix(rspack): prevent vfs concurrency issues for parallel builds

- package.json
- pnpm-lock.yaml
- pnpm-workspace.yaml
- src/esbuild/index.ts
- src/esbuild/utils.ts
Even though [`@ampproject/remapping`](https://npm.im/@ampproject/remapping) isn't deprecated on npm (yet), it's [repo](https://github.com/ampproject/remapping) is archived, so people should move to [`@jridgewell/remapping`](https://npm.im/@jridgewell/remapping)
> Development moved to [monorepo](https://github.com/jridgewell/sourcemaps)
> See https://github.com/jridgewell/sourcemaps/tree/main/packages/remapping for latest code.
---
I'm sure people from the wider @e18e ecosystem cleanup (like @43081j, @Fuzzyma, @outslept & @talentlessguy) will be very happy to see these kind of changes as well
> fix: update `@ampproject/remapping` to `@jridgewell/remapping`
